### ISSUE TITLE
sqlite internal table is not ignored

### ISSUE THREAD

**Issue by elandorr** [sqlalchemy/alembic#1062]
To get sqlalchemy to behave as expected with sqlite one must set `    __table_args__ = {"sqlite_autoincrement": True}`. (To get a `sqlite_sequence` table and monotonous sequences.)

If you then run `flask db migrate`, it will detect this internal table as a change:

`INFO  [alembic.autogenerate.compare] Detected removed table 'sqlite_sequence'`

Internal tables should be ignored.

Reference 2 years ago: https://github.com/miguelgrinberg/Flask-Migrate/issues/375

To the people who were looking for an interim fix:

In the env.py:
```
target_metadata = current_app.extensions["migrate"].db.metadata


def include_name(name, type_, parent_names):
    if type_ == "table":
        return name in target_metadata.tables
    else:
        return True
```

And under `run_migrations_online`:
```
        context.configure(
            ...
            include_schemas=True,
            include_name=include_name
```

This will include only tables in the current model in the autogeneration. It seems pretty clunky and I couldn't tell if there's a simple `exclude` option anywhere, but it will do for this particular task.

While I'm here, alembic also does not notice adding `sqlite_autoincrement` at all. If you manually set the AI flag, it messes up the next migration. A clean restart worked, but is obviously not very practical.

**Comment by zzzeek** [comment]
your recipe can be more accurately stated as:

```py
def omit_sqlite_sequence(object, name, type_, reflected, compare_to):
    if name == "sqlite_sequence":
        return False


def run_migrations_online() -> None:
    # ...

    with connectable.connect() as connection:
        context.configure(
            connection=connection, target_metadata=target_metadata,
            include_object=omit_sqlite_sequence
        )

        with context.begin_transaction():
            context.run_migrations()

```

the "system" tables for SQLite are assumed to be in https://www.sqlite.org/schematab.html and SQLAlchemy has no special logic for "sqlite_autoincrement", plus one could create a table with this name already, unless you know of a way to detect that this is a "system" table.   We can't change this in SQLAlchemy reflection right now.   

overall I think this is not really a problem usually because [sqlite documents that you really shouldn't use "AUTOINCREMENT" in most cases at adds  extra CPU, memory, disk space, and disk I/O overhead and should be avoided](https://www.sqlite.org/autoinc.html).    IMO it's a bad idea to rely on autogen pks being monotonic.

**Comment by zzzeek** [comment]
for now I think we just document how to avoid this one table for this uncommon use case

**Comment by zzzeek** [comment]
in the [recipes](https://alembic.sqlalchemy.org/en/latest/cookbook.html) section

**Comment by zzzeek** [comment]
ah this helps, [SQLite prohibits applications from creating objects whose names begin with "sqlite_". ](https://www.sqlite.org/fileformat2.html#intschema)

**Comment by zzzeek** [comment]
OK that's your workaround we will try to omit system tables in SQLAlchemy 2.0

upstream issue at https://github.com/sqlalchemy/sqlalchemy/issues/8234
