### ISSUE TITLE
Security: Log Injection

### ISSUE THREAD

**Issue by kneipp** [sqlalchemy/alembic#1083]
**Describe the bug**

Follow line in file [env.py](https://github.com/sqlalchemy/alembic/blob/873027160f88af277b73223e9fe33bfba315532f/alembic/templates/async/env.py) is flagged by Sonar as Log Injection:

```py
fileConfig(config.config_file_name)
```

Do we have better suggestions to solve this?

Configuring loggers is security-sensitive. It has led in the past to the following vulnerabilities:

[CVE-2018-0285](http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-0285)
[CVE-2000-1127](http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2000-1127)
[CVE-2017-15113](http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-15113)
[CVE-2015-5742](http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2015-5742)
Logs are useful before, during and after a security incident.

Attackers will most of the time start their nefarious work by probing the system for vulnerabilities. Monitoring this activity and stopping it is the first step to prevent an attack from ever happening.
In case of a successful attack, logs should contain enough information to understand what damage an attacker may have inflicted.
Logs are also a target for attackers because they might contain sensitive information. Configuring loggers has an impact on the type of information logged and how they are logged.

This rule flags for review code that initiates loggers configuration. The goal is to guide security code reviews.

**Have a nice day!**

**Comment by CaselIT** [comment]
Hi,

I don't think the report is valid, since the file config comes from trhe alembic.ini that's local to the project. And in any case env.py can be freely edited by users.
(From experience sonar has lots of false positives, since it doesn't keep the context into consideration)

Thoughts @zzzeek ?

**Comment by kneipp** [comment]
> I don't think the report is valid, since the file config comes from trhe alembic.ini that's local to the project. And in any case env.py can be freely edited by users.

Thank you for your reply and @zzzeek mention. I guess the alembic.ini should be deployed. In this context, users may have a real problem in production environments. We could provide a better template for these scenarios.

**Comment by kneipp** [comment]
> I don't think the report is valid, since the file config comes from trhe alembic.ini that's local to the project. And in any case env.py can be freely edited by users.

Thank you for your reply and @zzzeek mention. I guess the alembic.ini should be deployed. In this context, users may have a real problem in production environments. We could provide a better logging template for these scenarios.

**Comment by jvanasco** [comment]
This is not a valid security report.

The linked CVEs:

* CVE-2000-1127 - a local user can arbitrarily set the logging file, which will change it's permissions
* CVE-2017-15113 - passwords are logged in plaintext
* CVE-2015-5742 - passwords are logged in plaintext
* CVE-2018-0285 - excessive logging consumes all disk space.  note: this is inherent to pretty much any linux daemon and application

The full text of the Sonar flag is here: https://rules.sonarsource.com/python/RSPEC-4792

Note the following:

* This rule flags for review code that initiates loggers configuration. **The goal is to guide security code reviews.**

The page then offers secure coding practices to ensure sensitive data is not logged.

The alembic template implements a standard python idiom for log configuration.  Beyond that, alembic files are run by developers and production environment administrators - e.g. privileged users - and only during migrations.  Unprivileged users can not exploit this.  While it is possible this could result in plaintext secure credentials being logged, that would ultimately be due to an application developer purposefully logging that data, or due to the application developers storing sensitive data in plaintext.

> Do we have better suggestions to solve this?

Use another code analysis tool?  There is no issue.

> We could provide a better logging template for these scenarios.

Again, this is implemented using a standard idiom in python.  Note that it is merely invoking a standard library function: https://github.com/sqlalchemy/alembic/blob/873027160f88af277b73223e9fe33bfba315532f/alembic/templates/async/env.py#L2

The code analysis tool is simply letting you know that your application is implementing a logging facility, and you should audit any logging to ensure best security practices.

**Comment by zzzeek** [comment]
agree @jvanasco , running an auditing tool here doesn't actually find real problems, it's expected that actual CVEs are illustrated in order to report such issues.

**Comment by kultmet** [comment]
I have exactly the same problem.

<html>
<body>

 
--
if config.config_file_name is not None:
30 |   |   | fileConfig(config.config_file_name)Make sure that this logger's configuration is safe.

<br class="Apple-interchange-newline">
</body>
</html>

Unfortunately, the tool (sonar-cube) not only informs me about the problem, but also blocks the stage in the CI/CD pipeline. And if I delete these lines, then the alembic will not advertise his progress

I need help. How to disable this check

**Comment by zzzeek** [comment]
report a bug to the sonar-cube tool.   Python has a public API function called `fileConfig()`.  It accepts a string argument with the name of a config file.  Alembic allows you to tell it what the name of this config file is, and it stores it in a variable, and passes it to the function.   There is no inherent security implication to this operation and if a tool flags it, the tool should support a means of whitelisting this line of code.
