### ISSUE TITLE
Some mssql commands are not correctly quoted

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/alembic#1187]
Dropping a constraint with spaces using `mssql_drop_foreign_key=True` will results in an error

**Comment by sqla-tester** [comment]
**CaselIT** has proposed a fix for this issue in the **main** branch:

**Escape sql server constriant names** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/4463

**Comment by zzzeek** [comment]
can you explain the issue here?   "dropping a ...." what?  Can I see what SQL is being emitted that fails?  

not sure if im following the SQL correctly but it's selecting a column called `name` from `sys.default_constraints` or `sys.check_contraints`, that is

     SELECT [name] FROM sys.default_constraints

`[name]` is a quoted identifier, you wouldn't put QUOTENAME there, and it does not have spaces in it.

**Comment by zzzeek** [comment]
oh I see, QUOTENAME is running on the returned data, fine.

**Comment by CaselIT** [comment]
Sorry, the issue is when dropping constraints with names that need escaping. I've filled the missing words on the issue description.

Also this is a failry limited use case, since it affects only the `mssql_drop_*` kw args
