### ISSUE TITLE
Postgres CREATE INDEX CONCURRENTLY

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/alembic#277]
**Migrated issue, originally created by Iuri de Silvio ([@iurisilvio](https://github.com/iurisilvio))**

Is it possible to use the `CONCURRENTLY` statement to create my Postgres index?

**Comment by QuantumGhost** [comment]
Update regarding [this comment](https://github.com/sqlalchemy/alembic/issues/277#issuecomment-441885092):  

For anyone revisiting this issue and looking for a way to use `CREATE INDEX CONCURRENTLY` in pure Python code: instead of manually committing with `op.execute("COMMIT")`, you can leverage the [`autocommit_block`](https://alembic.sqlalchemy.org/en/latest/api/runtime.html#alembic.runtime.migration.MigrationContext.autocommit_block) context manager provided by Alembic. Here's an example:

```python
with op.get_context().autocommit_block():
    op.create_index(
        op.f('workflow_node_executions_tenant_id_idx'),
        "workflow_node_executions",
        ['tenant_id', 'workflow_id', 'node_id', sa.literal_column('created_at DESC')],
        unique=False,
        postgresql_concurrently=True,
    )
```

This approach ensures proper handling of PostgreSQL's "CONCURRENTLY" option in a clean and reliable way.
