### ISSUE TITLE
Record a history of when particular migrations were applied

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/alembic#309]
**note**: this feature is supplied via the [on_version_apply](https://alembic.sqlalchemy.org/en/latest/api/runtime.html#alembic.runtime.environment.EnvironmentContext.configure.params.on_version_apply) hook, with a full implementation supplied by the [audit-alembic](https://github.com/jpassaro/Audit-Alembic) project.

**Migrated issue, originally created by Josh Kupershmidt ([@schmiddy](https://github.com/schmiddy))**

I was a little surprised to see that the `alembic_version` table records only the current `version_num`, without even a timestamp indicating when that version was applied. For forensic purposes, it's often handy to know when past migrations were applied to a target database, e.g. when trying to track what happened to a database in the past, determine why some errors popped up in a production database around some time, etc. The `alembic history` command is useful, but not quite what I'm looking for, since it doesn't tell me when the migrations were actually run in production.

(I'm currently using alembic 0.6.7, but didn't see this feature requested or mentioned anywhere else, so am assuming the situation is the same in the bleeding edge.)

**Comment by zzzeek** [comment]
just a note, I think separate auditing table would be much easier to implement and also it should be enabled via an option to suit environments that don't currently have such a table present.

**Comment by jasenj1** [comment]
See https://github.com/jpassaro/Audit-Alembic for an example of how this could be done. It would be nice to update and absorb this project into Alembic proper.

**Comment by Nogias9x** [comment]
Hi,
Do we any news for this?
I think this would be an awesome feature to have. The mechanism is proved to work well by `Sequelize` :)

**Comment by kenho811** [comment]
I am a newbie to database version control and have looked into flyway (java), yoyo-migrations (python) and finally alembic (python).

As a heavy python user, I would love to do everything in python. However, the lack of `alembic_version_history` table really makes auditing difficult.

It would be great to see it implemented like in flyway and yoyo-migrations!

**Comment by zzzeek** [comment]
good idea at #1075, record the first line of the "message" also.

**Comment by Maimonator** [comment]
Anything new around this?

**Comment by zzzeek** [comment]
you'd see it here first

**Comment by CaselIT** [comment]
an additional use case that may make use of this feature could be the one mentioned in #1298

**Comment by Bladieblah** [comment]
Yearly bump, this is an important feature for any use-case that is not a hobby project

**Comment by zzzeek** [comment]
the https://github.com/jpassaro/Audit-Alembic project already includes a working implementation for this feature for those who want drop-in, and the [on_version_apply[(https://alembic.sqlalchemy.org/en/latest/api/runtime.html#alembic.runtime.environment.EnvironmentContext.configure.params.on_version_apply) hook was added to support this use case for any variation.     The specifics of how/where each version is logged, e.g. database table, log file, etc. are best left open ended here since there are many ways to do this.  As you said, this feature appeals towards non hobby-project use cases so beyond adding something short to [Cookbook](https://alembic.sqlalchemy.org/en/latest/cookbook.html) , Alembic's side here is as far as i think it should go.

**Comment by CaselIT** [comment]
I think it would still nice to have at some point, but we can probably reopen if someone wants to contribute it

**Comment by Bladieblah** [comment]
The audit_alembic package is 7 years old and longer works with the current version of alembi

**Comment by zzzeek** [comment]
It's simple in its implementation and I think all the programmers here who are interested in a more polished version of this functionality should contribute towards making something available, either a new package, a good recipe in our docs, etc.  otherwise this issue really feels like "zzzeek please write this for us, document it, then maintain it forever including responding to all our complaints and issues going forward" and I don't have a lot of resources these days for a big ask like that.

**Comment by Bladieblah** [comment]
I made it compatible with the current api, the tests are very broken though. I'll try to get them patched up and see if the original guy is willing to merge it.
https://github.com/Bladieblah/Audit-Alembic/tree/master

**Comment by zzzeek** [comment]
> I made it compatible with the current api, the tests are very broken though. I'll try to get them patched up and see if the original guy is willing to merge it. https://github.com/Bladieblah/Audit-Alembic/tree/master

thanks.    this helps a lot

**Comment by jpassaro** [comment]
cross-posting, in brief, my response to that PR.

I'm excited that there's apparently some interest in this functionality in the community! unfortunately, i haven't used sqla since about the time i wrote this, and in fact never really used Alembic in prod - so I'm not really part of this community anymore and can't maintain responsibility for a community project. 

This stands as a sort of toy POC but others are welcome to fork it and maintain it. i think @Bladieblah's PR is a good step in that direction. 

either way if a successor project emerges I'll link to it in my README. I'm also open to transferring the PyPI name.

**Comment by Bladieblah** [comment]
Thanks for the quick response @jpassaro! @zzzeek would you be interested in hosting the repo in the sqlalchemy org? I'll keep maintaining it of course

**Comment by zzzeek** [comment]
probably not for now, everything in sqlalchemy/ are my own projects and they all follow a very specific layout / testing / release / etc
