### ISSUE TITLE
Enum value changes are not detected in sqlite or mysql (non-native enum setting)

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/alembic#329]
**Migrated issue, originally created by Robert Buchholz ([@rbuchholz](https://github.com/rbuchholz))**

Given a table with a column such as:

```
            sa.Enum('a', 'b'),
```

If I change it to
```
            sa.Enum('a', 'b', 'c'),
```

there will be no change detected in either MySQL or Sqlite (these two I tried).

**Comment by grubbins** [comment]
> on a backend which doesn’t support ENUM directly

For mysql specifically (not sqlite), surely that is a backend that **does** support ENUM directly? The type of my column in mysql is `enum`, and when reflecting, sqlalchemy has type `sqlalchemy.dialects.mysql.enumerated.ENUM`. But if I add a value to the enum class, still no change is detected.

I understand if this is not implemented, but this ticket was closed in reference to the docs, and surely the docs say that it is implemented?

**Comment by zzzeek** [comment]
> 
> I understand if this is not implemented, but this ticket was closed in reference to the docs, 

#779 is added

> and surely the docs say that it is implemented?

it's not.   type comparison was vastly improved in #605 but I don't know that we established this covers MySQL ENUM arguments.

**Comment by grubbins** [comment]
Looking at this further (for mysql), I realised that if the number of enum values is the same, then changes in the list of possible enum values are detected - but, if you add an enum item, they are not. That's because in `alembic.ddl.impl` in `DefaultImpl._column_args_match`:
```python
        if (
            len(meta_params.args) == len(inspected_params.args)
            and meta_params.args != inspected_params.args
        ):
            return False
```
i.e. if the length of the args list is different, then we ignore the args values and detect no change.

Detecting a change whenever the length of the args lists are different would make sense, but I'm sure it produces tons of false positives - I already saw that myself with spurious `INTEGER(display_width=11) to Integer()` conversions.

As a workaround I tried adding this:
```python
        if (
                meta_params.token0 == 'enum'
                and len(meta_params.args) != len(inspected_params.args)
        ):
            return False
```

This does actually work for my experiment - I added an item to my enum, and the correct migration script was produced.

@zzzeek maybe this issue should re-open and refer specifically to mysql native enums (forget sqlite)? Or shall I open a new one?

**Comment by hughhan1** [comment]
I am still having this problem as well in MySQL, using `flask_sqlalchemy`'s `db.Column` to define the columns on my model. Regardless of whether I use `db.Enum` or `sqlalchemy.dialects.mysql.enumerated.ENUM` to define the type of the column, Alembic is not detecting any changes when I add new values to the enum.

But in contrast, if I define a _new_ column using the `db.Enum` type, Alembic successfully generates the migrations necessary to create the enum column with the proper values.

I also confirmed that when reflecting, the column's type is `sqlalchemy.dialects.mysql.enumerated.ENUM`.

**Comment by N-Demir** [comment]
Still having this issue
