### ISSUE TITLE
JSONB -> ARRAY ALTER failure

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/alembic#427]
**Migrated issue, originally created by Zsolt Ero ([@hyperknot](https://github.com/hyperknot))**

I am changing a column type from JSONB to ARRAY (in PG 9.6).

I guess it should be dropped and re-created, but maybe it can be altered, I don't know, but it results in an error.

Migration script:

```
    op.alter_column('images', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.ARRAY(sa.Unicode()),
               nullable=True)
```

Error:

```
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) column "tags" cannot be cast automatically to type character varying[]
HINT:  You might need to specify "USING tags::character varying[]".
 [SQL: 'ALTER TABLE images ALTER COLUMN tags TYPE VARCHAR[] ']
```

**Comment by CaselIT** [comment]
Stumbled on this while running a migration Strung -> integer.

There seems to be a problem in the generation of the docs, since there is no reference of  `postgresql_using` in the docs.

The documentation in the alter column op, https://github.com/sqlalchemy/alembic/blob/d791c575e95614f53c282a9f22166646dc46b9a0/alembic/operations/ops.py#L1651

is not in any page of the online docs.
https://alembic.sqlalchemy.org/en/latest/api/operations.html?highlight=alter_columns#alembic.operations.ops.AlterColumnOp.alter_column

I'll open a new issue regarding the docs, since I think this could be closed
