### ISSUE TITLE
add --package flag to alembic init to support building as package

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/alembic#463]
**Migrated issue, originally created by Luke Schlather ([@lukeschlather](https://github.com/lukeschlather))**

When I run alembic init, it generates alembic.ini, alembic, and alembic/versions/ .

I run this in a namespaced directory (e.g. database) under a python package. It would be nice if alembic automatically detected that it was being created within a python package, and modified the Manifest, and/or added __init__.py files to ensure it is distributed along with the package.

As an example, suppose I had a structure like:

```
#!

* mypackage
** setup.py
*** database 

```

If I were to run "alembic init" in the database directory, it would be nice if alembic init detected the setup.py in the root of the project, created a MANIFEST.in if need be, and created __init__.py files so it instead looks like:

```
#!

* mypackage
** setup.py
** MANIFEST.in
*** database 
**** alembic/__init__.py
**** alembic/versions/__init__.py
```

**Comment by zzzeek** [comment]
looking at this again, trying to figure out what to do.

1. I really dont think it's appropriate to generate a MANIFEST.in as Alembic makes no assumptions about what kind of environment it's being run within.

2. Similarly, editing MANIFEST.in would be hugely surprising to most people, not to mention error prone, and also unnecessary if there are `__init__.py` files present.    Otherwise, why doesn't "sphinx init" for example also search for or edit MANIFEST.in.  This would be really inappropriate since a code generation tool should not be trying to also be a packaging tool, unless it's actually being used as a packaging tool.

3. I know above I said I'd search in sys.path but I don't know why I said that, sys.path can have any number of paths within it.

What I can do, that is easy and is the kind of thing that people ask for, is that if you say "--package", it simply puts the two `__init__.py` files there as well, but everything else is the same.  going to do that for now.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Add --package flag to write __init__.py files** https://gerrit.sqlalchemy.org/1471
