### ISSUE TITLE
revise approach for alembic.op import so that an explicit object is imported, how to make Operations methods statically available?   (or not)

### ISSUE THREAD

**Issue by Teemu** [sqlalchemy/alembic#573]
Some of the magic that Alembic uses under the hood for operations also means that the editors are unable to autocomplete the methods. This might not sound like a huge problem but it's a massive time waste for people to check what method belongs where and in which order.

It seems like in the past Alembic contributed to Python-skeletons but that seems deprecated in favor of TypeShed.

My experimental hacky fix for this was just to populate `alembic/op.py` with mock methods:

````
from .operations.base import Operations

def add_column(table_name, column, schema=None):
    pass
def alter_column(table_name, column_name, nullable=None, comment=False, server_default=False, new_column_name=None, type_=None, existing_type=None, existing_server_default=False, existing_nullable=None, existing_comment=None, schema=None, **kw):
    pass
def batch_alter_table(table_name, schema=None, recreate='auto', copy_from=None, table_args=(), table_kwargs={}, reflect_args=(), reflect_kwargs={}, naming_convention=None):
    pass
def bulk_insert(table, rows, multiinsert=True):
    pass
def create_check_constraint(constraint_name, table_name, condition, schema=None, **kw):
    pass
def create_exclude_constraint(constraint_name, table_name, *elements, **kw):
    pass
def create_foreign_key(constraint_name, source_table, referent_table, local_cols, remote_cols, onupdate=None, ondelete=None, deferrable=None, initially=None, match=None, source_schema=None, referent_schema=None, **dialect_kw):
    pass
def create_index(index_name, table_name, columns, schema=None, unique=False, **kw):
    pass
def create_primary_key(constraint_name, table_name, columns, schema=None):
    pass
def create_table(table_name, *columns, **kw):
    pass
def create_table_comment(table_name, comment, existing_comment=None, schema=None):
    pass
def create_unique_constraint(constraint_name, table_name, columns, schema=None, **kw):
    pass
def drop_column(table_name, column_name, schema=None, **kw):
    pass
def drop_constraint(constraint_name, table_name, type_=None, schema=None):
    pass
def drop_index(index_name, table_name=None, schema=None, **kw):
    pass
def drop_table(table_name, schema=None, **kw):
    pass
def drop_table_comment(table_name, existing_comment=None, schema=None):
    pass
def execute(sqltext, execution_options=None):
    pass
def f(name):
    pass
def get_bind():
    pass
def get_context():
    pass
def inline_literal(value, type_=None):
    pass
def invoke(operation):
    pass
def rename_table(old_table_name, new_table_name, schema=None):
    pass
def create_check_constraint(constraint_name, condition, **kw):
    pass
def create_exclude_constraint(constraint_name, *elements, **kw):
    pass
def create_foreign_key(constraint_name, referent_table, local_cols, remote_cols, referent_schema=None, onupdate=None, ondelete=None, deferrable=None, initially=None, match=None, **dialect_kw):
    pass
def create_index(index_name, columns, **kw):
    pass
def create_primary_key(constraint_name, columns):
    pass
def create_unique_constraint(constraint_name, columns, **kw):
    pass
def drop_column(column_name, **kw):
    pass
def drop_constraint(constraint_name, type_=None):
    pass
def drop_index(index_name, **kw):
    pass

# create proxy functions for
# each method on the Operations class.
Operations.create_module_class_proxy(globals(), locals())
````

and it works:

<img width="748" alt="Screenshot 2019-06-04 at 15 06 07" src="https://user-images.githubusercontent.com/53298/58878173-4da30580-86db-11e9-995a-31612ad547d7.png">

I am curious to hear approaches for solving this.

**Comment by zzzeek** [comment]
make the top of your script.py.mako like this:

```
"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}

"""
from alembic.operations import Operations
from alembic import op as _op
op = Operations(_op._proxy.migration_context, _op._proxy.impl)

```

the thing that happens in alembic.op will have to change at some point anyway because we will eventually have pep484 annotations that won't appreciate how that works.

**Comment by zzzeek** [comment]
oh i guess that won't work because the methods on Operations are also dynamic and your editor is only doing static analysis.

**Comment by zzzeek** [comment]
Also I've never heard of TypeShed or Python-skeletons and Alembic has not contributed to these projects.

**Comment by zzzeek** [comment]
yeah, Operations and op.* are namespaces.    editors that do autocomplete need some way to support dynamic namespaces, as I think about this I'm leaning towards probably nothing I can do on this end.

**Comment by zzzeek** [comment]
yah that's someone else.

the most likely solution here is that we provide a .pyi file, which I'm sure your editor knows how to read, but the problem is that this is only an 80% solution.  The Operations class is a 
dynamic namespace because new methods can be added by anyone by registering them.    

The normal way we'd support this pattern without any dynamism is that migration files have a list of "from alembic.operations import create_table" kinds of statements in it, and someone's extension would be "from myextension import create_sequence".   But this means migration files have hardcoded imports in them which makes it more difficult to change things later, because migration files are supposed to never have to change even with new versions of things.      it also makes the imports a lot more involved to write out from autogenerate as well as when writing migrations by hand (unless your editor is writing them automatically :) ).

it's kind of different ways of working and migration files are leaning towads "mostly automated writing" since everyone uses autogenerate for 90% of their file.

**Comment by Frozenball** [comment]
> the most likely solution here is that we provide a .pyi file, which I'm sure your editor knows how to read, but the problem is that this is only an 80% solution. The Operations class is a
dynamic namespace because new methods can be added by anyone by registering them.

Even 80% is probably good enough since nobody expects Python autocomplete to be perfect and adding new methods seem rare enough (proof me wrong).

> The normal way we'd support this pattern without any dynamism is that migration files have a list of "from alembic.operations import create_table" kinds of statements in it, and someone's extension would be "from myextension import create_sequence". But this means migration files have hardcoded imports in them which makes it more difficult to change things later, because migration files are supposed to never have to change even with new versions of things. 

Isn't this problem already with current `op` approach? I mean the operations can never change anyway.

> it's kind of different ways of working and migration files are leaning towads "mostly automated writing" since everyone uses autogenerate for 90% of their file.

I tend to agree with this. The only reason why I am complaining about this in the first place is that the check constraints replacements are not generated automatically so I am digging through documentation for their syntax.

**Comment by zzzeek** [comment]
> > the most likely solution here is that we provide a .pyi file, which I'm sure your editor knows how to read, but the problem is that this is only an 80% solution. The Operations class is a
> > dynamic namespace because new methods can be added by anyone by registering them.
> 
> Even 80% is probably good enough since nobody expects Python autocomplete to be perfect and adding new methods seem rare enough (proof me wrong).

I'd like it to be less rare and the I'd want the solution to include documentation at https://alembic.sqlalchemy.org/en/latest/api/operations.html#operation-plugins for how this support can be added.

Additionally, the addition of a .pyi file needs to have some process that tests it against the interface of the actual op method, because it's definitely going to go out of sync otherwise.  I'm not sure if theres a script that can be added to tox.ini or some other programmatic test.

> 
> > The normal way we'd support this pattern without any dynamism is that migration files have a list of "from alembic.operations import create_table" kinds of statements in it, and someone's extension would be "from myextension import create_sequence". But this means migration files have hardcoded imports in them which makes it more difficult to change things later, because migration files are supposed to never have to change even with new versions of things.
> 
> Isn't this problem already with current `op` approach? I mean the operations can never change anyway.

ops do change in that they have new arguments added to them and there have even been some changes to the argument signatures, but as far as things like "create_table" and "alter_column" always existing that's not a long bet.    the issue is more about more specific module paths having to change.  "op" is intended to be a generic namespace.  namespaces are not unusual things in Python they are even in "import this". 

It's possible that we can support both styles (though I don't like this idea for the extensibility reason above), as it stands there are millions of alembic version files that are doing "import op" so that has to always work.


> 
> > it's kind of different ways of working and migration files are leaning towads "mostly automated writing" since everyone uses autogenerate for 90% of their file.
> 
> I tend to agree with this. The only reason why I am complaining about this in the first place is that the check constraints replacements are not generated automatically so I am digging through documentation for their syntax.

I think long term the pep484 / pyi thing will happen to alembic, not to mention py3 only, and improve this situation but there will be a lot of considerations to make along the way and also waiting for tooling to come on board and help out.

**Comment by zzzeek** [comment]
i don't have plans to make changes on this right now.   alembic wants to have type annotations eventually but that's a long way down the road and it's not clear how that will work with the op namespace.

*if* someone wanted to give us a .pyi file, and some way to ensure it gets tested when we change things, and also we can confirm the IDEs use the .pyi file, I am open to that, but I don't have plans to do that myself right now.
