### ISSUE TITLE
Long running auto-generate

### ISSUE THREAD

**Issue by lucasnad27** [sqlalchemy/alembic#580]
I'm trying to get a fairly large database (8477 tables, and a handful of schemas) and auto-generating a migration is taking a very long time. Clocking in around ~70 minutes!

I haven't been able to find any information about what could be causing this long load time. I'm going to try and run `strace` on the next generation and see if I can figure out where it's getting hung up, but any help would be greatly appreciated.

**Comment by zzzeek** [comment]
hi there -

The purpose of autogenerate is to create a diff of a SQLAlchemy schema model that exists as Python source code, against the current tables present in a relational database.   So if you are pointing autogenerate at a multi-schema database with 8500 tables, that implies that your Python source code itself would at some point contain the same number of Table objects and/or ORM models, all declared fully explicitly in Python code.   

if you don't currently have 8500 Table / ORM models declared in your source code, there's not much reason to have autogenerate be including these tables in an autogenerate sweep.  

There is a feature that allows tables you don't want considered as part of autogenerate to be skipped, however in the interests of being a rich API it reflects the Table object first, so this wouldn't help the issue of performance as it's the reflection of the Table object that is the most time consuming.  https://github.com/sqlalchemy/sqlalchemy/issues/4379 seeks to improve for this, however if that issue is implemented, it still would require changes within Alembic so that the list of Table objects are retrieved en-masse rather than one at a time from the list of names as is the current source.

There may be ways of affecting the list of names to be reflected before this is done so, however, it's not clear if this is what you want to do or what your ultimate goal is.   It seems like autogenerate might not be what you're looking for in the first place.

**Comment by zzzeek** [comment]
i would add a new hook `include_name` to complement [include_object](https://alembic.sqlalchemy.org/en/latest/api/runtime.html?highlight=include_object#alembic.runtime.environment.EnvironmentContext.configure.params.include_object), if your use case were that you wanted to autogenerate against a small subset of these 8500 tables which you can filter by name alone.

**Comment by lucasnad27** [comment]
Thanks for the quick response @zzzeek 

This database has been in production for a few years without any proper migrations so trying to put a proper migration path in place is a little painful. I might be dreaming too big for auto-generated migrations 😅 

Nonetheless, I've got a handful of exclude rules when configuring alembic's context, but as mentioned, that's not helping during the table introspection process. I'll have to talk internally with my team and see if we still want to go down the auto-generation path or if we use alembic to generate empty migrations and fill them in from there. Not ideal, but then again, neither is our current situation. 

Thanks again for your help. Feel free to close this issue if you'd like. Either way, I'll update this thread with our final course of action.

**Comment by limse10** [comment]
Hello! Given that https://github.com/sqlalchemy/sqlalchemy/issues/4379 has been implemented, is it possible to look into using the new API to optimize alembic autogenerate for a large number of schemas/tables?

**Comment by zzzeek** [comment]
@CaselIT it looks like if compare.py could call into inspector._get_reflection_info() directly this would be the best way for it to have a structure from which it can get Table objects but also lists of raw foreign key / index / unique constraint data.  otherwise we'd have to package up similar caching into _InspectorConv which might as well just store the _ReflectInfo (optionally too, since we still support 1.4).  let me know if you have ideas

**Comment by CaselIT** [comment]
I can look into it. Can we open another issues for it?

**Comment by zzzeek** [comment]
yeah

**Comment by limse10** [comment]
Thank you so much! is there an issue created to track this yet?

**Comment by CaselIT** [comment]
no, there isn't an issue for it as far as I know
