### ISSUE TITLE
alembic 1.2.0 broke the alembic.command.stamp() revision parameter

### ISSUE THREAD

**Issue by toabctl** [sqlalchemy/alembic#601]
Trying to use OpenStack services with alembic 1.2.0 (currently 1.1.0 is used) is breaking a lot of services with (Ironic example):

```
[...]
    b'  File "ronic/ironic/db/sqlalchemy/migration.py", line 99, in stamp'
    b'    return alembic.command.stamp(config, revision=revision)'
    b"TypeError: stamp() got an unexpected keyword argument 'revision'"
```

Looks like the `stamp` method does no longer accept the parameter `revision` (done in commit fdcc5bf973fec758eaf67cf8e8ad48985caffb65).

I wonder if it would be possible (until 2.0.0 comes up) to support `revision` and `revisions` as parameter to be backward compatible?

Also oslo.db is affected. It tries to use the `revision` parameter. See https://opendev.org/openstack/oslo.db/src/branch/master/oslo_db/sqlalchemy/migration_cli/ext_alembic.py#L92

**Comment by zzzeek** [comment]
someone actually noted that I changed this name, and I asked, you're not actualy using the positional argument as a kw are you, and they said no, and I was like, OK, great.   But then here we are.   Alembic is actually tested against neutron and oslo.db, I can add more alembic-using projects like ironic since nova/keystone have unfortuantely never switched.

There's a decorator I can use to allow for both kw args but also it should be passed positionally.

**Comment by sqla-tester** [comment]
**Thomas Bechtold** has proposed a fix for this issue in the **master** branch:

**Fix alembic.command.stamp() signature and allow revision again** https://gerrit.sqlalchemy.org/1477

**Comment by zzzeek** [comment]
also why didn't oslo.db's test fail in my own CI

**Comment by zzzeek** [comment]
also as far as 1.2 etc we don't use pure semver, see https://www.sqlalchemy.org/download.html#versions.  there's never going to be an alembic 2.0
