### ISSUE TITLE
Migration script wrongly generated when table name is all uppercase

### ISSUE THREAD

**Issue by sergiomafra** [sqlalchemy/alembic#628]
I'm developing an API with Flask and I'm using flask-sqlachemy to create models and flask-migrate to generate migration scripts and upgrade the database. It is an Oracle database.

The first script ran smoothly and created the tables. But the next one where I changed a constraint on a column of a tablel wasn't created right. It is trying to create again all the tables and trying to delete the same tables with lowercase letters.

My guess is when I create tables with uppercase letters, the script transforms it to lowercase at somepoint and check if it exists as a lowercased string. The tables were created fine with all uppercase letters.

Model example:

`class Blacklist(db.Model):
''' IPs from users that continuously offend the system end up here '''

__bind_key__ = None
__tablename__ = 'SCR_BLACKLIST'

ID_BLACKED = db.Column(db.Integer, primary_key=True)
IP = db.Column(db.String(15), nullable=False)
BLACKLIST_INSERTION_TYPE = db.Column(
    db.Integer,
    db.ForeignKey('SCR_BLACKLIST_INSERTION_TYPES.ID_BLACK_TIPO'),
    nullable=False)
RATIO_LIMIT = db.Column(db.Integer, nullable=False, default=0)
IP_STATUS = db.Column(db.Boolean, nullable=False)
INSERTION_DATE = db.Column(db.DateTime, nullable=False, default=tb.now())
REMOVED_DATE = db.Column(db.DateTime, nullable=False)

def __repr__(self):
    print(f'<Blacklisted IP: {self.IP}>')`

Is there a way to workaround or solve this issue?

**OS:** Ubuntu 18.04
**Database:** Oracle
**Packages:** flask-sqlalchemy, flask-migrate

**Comment by zzzeek** [comment]
hi -

it is extremely unusual to have a tablename that is case **sensitive** UPPERCASE on Oracle.  were these tables created using quotes for the names ?  that is, 'CREATE TABLE "UPPERCASE_NAME" ' ? 

Otherwise, assuming these are normal, case insensitive names that you just happen to observe as UPPERCASE in your Oracle console, that is normal - specify table names in all lowercase on the SQLAlchemy side.    see https://docs.sqlalchemy.org/en/13/dialects/oracle.html#identifier-casing
