### ISSUE TITLE
Numeric fields with scale but no precision do not work as expected.

### ISSUE THREAD

**Issue by wapiflapi** [sqlalchemy/alembic#666]
When defining a field in a model as `sa.Numeric(scale=2, asdecimal=True)` I expect the database to do the rounding for me, in this case with two decimal digits in the fractional part.

However if `scale` is given but no `precision` is given then `alembic` generates SQL resulting in ` price NUMERIC,`, **without the scale!  This is not intuitive**, as a developer I set a parameter (`scale` in this case) which has **no** effect at all so that's probably either a bug or a mistake on my part. 

I think either there should be a warning or error when `scale` is set but no `precision` is given (as this doesn't work.) or it should have a default value for `precision` in that case.

Note that when the database doesn't support NUMERIC (for example sqlite) then the behavior of this example works as expected since `sqlalchemy` uses python's `Decimals`  to do the correct (intuitive) rounding.

Workaround is to set a `precision` manually then it works. But it is not clear that the database isn't doing what the developer expects unless they manually inspect the SQL or database.

**Comment by zzzeek** [comment]
hi there-

the rendering of a datatype on a particular backend is an issue that should be reported to https://github.com/sqlalchemy/sqlalchemy.

Also, the Numeric type by itself can't decide if a certain database-specific numeric type needs to have "precision" set or not.  The place where "scale is ignored" happens in the dialects, like in Oracle https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/dialects/oracle/base.py#L701 .

So what I would like you to do is:

1. close this issue, because rendering of Numeric is a SQLAlchemy issue

2. open an issue at https://github.com/sqlalchemy/sqlalchemy

3. please provide **specifics** on what database backend you are using as well as an MCVE test case.  Here is one:

```
$ python
Python 3.7.6 (default, Dec 19 2019, 22:50:01) 
[GCC 9.2.1 20190827 (Red Hat 9.2.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sqlalchemy import Numeric
>>> from sqlalchemy.dialects import oracle
>>> print(Numeric(scale=7).compile(dialect=oracle.dialect()))
NUMERIC
>>> print(Numeric(precision=10, scale=7).compile(dialect=oracle.dialect()))
NUMERIC(10, 7)

```

for as many database backends as you feel like testing and noting, that would be extremely helpful as this needs to be fixed in each dialect that has the issue. thanks!

**Comment by wapiflapi** [comment]
Thanks @zzzeek for the extremely quick answer! You helped me understand the issue a bit better. I'll close this issue and open one on the sqlalchemy repo after having done some more testing. (probably not before the weekend.)
