### ISSUE TITLE
Option to disable error revision.ResolutionError

### ISSUE THREAD

**Issue by AlexandrSuperTramp** [sqlalchemy/alembic#691]
Hi,

I am using Kubernetes with Helm to deploy my web application. Sometimes the are errors in the newly deployed version and I try to rollback for the previous stable version, if the new application version has any new migration Helm Job (`alembic upgrade head`) failed with error and rollback failed too.
``` 
ERROR [alembic.util.messaging] Can't locate revision identified by 'dea3b669039f'
  FAILED: Can't locate revision identified by 'dea3b669039f'
```
An error occurred because the previous application version hasn't new migration, but in DB alembic save migration id.

I solved the problem by handle it in env.py
```
def run_migrations_online() -> None:
    """Run migrations in 'online' mode.

    In this scenario we need to create an Engine
    and associate a connection with the context.

    """
    ....
    ....
        with context.begin_transaction():
            try:
                context.run_migrations()
            except CommandError as e:
                if "Can't locate revision identified by" in str(e):
                    print(f'Migration error: {e}')
                else:
                    raise e
```

Would it be possible to have the option in config to disable this error without handling with try-except?

Regards,

**Comment by zzzeek** [comment]
Hi - 

I'm not understanding what the problem is.   if alembic sees state in the database that doesnt match its local information, it can't proceed.  it looks like you are just changing the error message that the alembic command would emit and perhaps causing it to exit without an error code.    If you want a unix command to not halt your shell script, you can just do this:

    alembic upgrade head || echo 'command failed' && true

**Comment by Arfey** [comment]
Hey. I think it would be great if we had this option.

So, the main problem is that after bad release `helm` try to rollback to previous release and apply migration. Migrations files don't have a new migration file because it previous release . As result alembic  raise an error.

Django migration works some like propose in issue. If we have applied migration greater than current so don't do anything.

```
alembic upgrade head || echo 'command failed' && true
```

This will work, but will skip all the errors, and I think this is not what we want.

ps:i know that we can write smart bash script but actually i expect this behaviours out of the box.

**Comment by zzzeek** [comment]
I apologize, I have no idea what is being asked for here.   Alembic throws an error when it can't continue.  I see a patch above that seems to do nothing more than change this "raise an error" to "print the error" and there is no substantive difference in these behaviors.    When you say "skip all the errors", from what I can see, there is just one, and it is an error that means alembic cannot continue.      If you have modified your env.py to perhaps iterate through multiple databases or something like that, please share that information here.  If this is the case, then what you are doing is already the correct approach, catch the exception you don't want it to raise and then continue.

**Comment by zzzeek** [comment]
please share the stack trace as well, because to my knowledge, that error message means you are running against a database that has a non-existent version in its alembic_version table.   if there's something else causing this error then perhaps I can understand how exactly you would want the transaction to continue.

**Comment by zzzeek** [comment]
oh, the use case is, use a previous version of the application to perform an alembic downgrade which does not feature the newer migratoin?    I don't see how that's possible either, alembic can't downgrade your database if it is on a version it knows nothing about.

**Comment by Arfey** [comment]
Sorry for my poor explanation 😅

```
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
ERROR [alembic.util.messaging] Can't locate revision identified by '61cac7fb7e12'
FAILED: Can't locate revision identified by '61cac7fb7e12'
```

yes, u a right. Error connected with that previous version of the application don't have a new migration file and we don't use alembic downgrade when try to rollback (we have some reasons for that).

We use that approach (without downgrade) in django with success and expected the same similar with alembic.

In hack which u can see above @AlexandrSuperTramp try to handle only error with connected with this case and don't skip all other errors. But in this approach i see problems. When u or other contributors will change error message this will not work 😀

It's not problem for us use bash script with error handling but i think that will be nice to have this option out of the box.

thx.

**Comment by CaselIT** [comment]
Ok, I believe I understand what it is asked here:
Problem: they do not want alembic to exit with error when a revision error happens, but still exit with error in other cases.

This means that `alembic ... || true` does not work since that command will always have success.
The approach they use it to check the string of the `CommandError` to check if it matches `"Can't locate revision identified by"`, but this solution is not the best, since it that message gets changed the workaround does not work.
https://github.com/sqlalchemy/alembic/blob/53c15cf1c75232f3f19d70c093c6c93c30a679f8/alembic/script/base.py#L191-L194

I believe that what they are asking is a way of suppressing this type of error, or a way of better identifying the errors.
@Arfey @AlexandrSuperTramp please let me know if I understood correctly

I think we could raise a subclass of command error in this case, but it would not be very scalable,
or we could maybe add a `cause` to `CommandError` and set it to a predefined list of things that would unlikely to change.

**Comment by zzzeek** [comment]
yes I wondered if that's the issue, that CommandError is too generic.    so good news, Python 3 already has a "cause" and we do honor this correctly:

```
(Pdb) !e
CommandError("Can't locate revision identified by 'bc7e28ed1604'")
(Pdb) !e.__cause__
ResolutionError("No such revision or branch 'bc7e28ed1604'")

```

that's as specific as it gets

**Comment by CaselIT** [comment]
then I guess it's only a question of better documentation

**Comment by CaselIT** [comment]
Where would it be a good place to an example of this? Maybe the cookbook?

**Comment by zzzeek** [comment]
the cookbook is for use cases, and I still don't actually see the use case here :).   IIRC, if alembic has this error, that's the first thing it tried to do, so it did not run any migrations.  There's nothing in the transaction, nothing to commit, it can't continue, we're done.    The command should fail.

Still not clear here if what's happening is they are running a migration on multiple engines, some of which pass and some of which fail.        I think as far as a "use case", if the environment is expecting to hit databases with this issue, I think it is safer to do a positive check first that the database is in the correct state before trying to do anything.   Because it is not a guarantee that the failure mode they are getting is in fact what will always happen.

So then it would be this "positive check" that we are looking for.   like "database_is_correctly_versioned_for_this_history()" or something like that.

**Comment by Arfey** [comment]
Actually i think so `__cause__` enough for us and we can correctly handle current error. So thanks for suggest.

Also in last time i try to explain why error is not a good in our case (a lot of project do the same).

We have one database and don't use downgrade in alembic after rollback. So "append only" policy or backward compatibility, up to u.

workflow in CI:

*step 1*
_deploy new version: _

- apply migration to head
- if migration applied with success so switch to new version of application

if we have some error with new version of application we start deploy previous version of application.

*step 2*
_deploy previous version:._

- apply migration to head
- if migration applied with success so switch to  previous version of application

So on a step 2 we got an error.

```
Can't locate revision identified by '61cac7fb7e12'
```

and as result we'll not switch to  previous version.

As u can see it's a problem in our use case. Django save all list of applied migration and check if migration are in table and if no so don't apply this migration and don't raise any error.

Thank u for quick response.

**Comment by AlexBohdan** [comment]
@CaselIT you understand correctly 

Use __cause__ better solution for my problem thanks
