### ISSUE TITLE
Calling Script upgrade function directly

### ISSUE THREAD

**Issue by yoobles** [sqlalchemy/alembic#692]
**Describe your question**
I need to implement migrations for submodules of a project so I have a few problems to address:

- Locate the appropriate migrations directory
- Store the submodule `version_num` somewhere
- Call the right `upgrade()` functions

Most of this is accomplished with the `ScriptDirectory` module and `ScriptDirectory.iterate_revisions`. But I'm not sure if I have the right approach for calling the upgrade function. 

Is calling `Script.module.upgrade()` in a loop correct? Or is there a better way to bulk run a list of `Script` objects?

**Useful links**
https://alembic.sqlalchemy.org/en/latest/api/script.html
https://alembic.sqlalchemy.org/en/latest/api/script.html#alembic.script.Script

**Have a nice day!**

**Comment by yoobles** [comment]
Actually I've realized that doing that causes `from alembic import op` to return None. Is there a better way to do this?

**Comment by zzzeek** [comment]
hi there -

I'm not sure what you're doing but Alembic supports multiple environments directly using the --name flag:

https://alembic.sqlalchemy.org/en/latest/cookbook.html#run-multiple-alembic-environments-from-one-ini-file

if you have separate alembic_version tables and a fixed set of sub-areas in a project, that's how you would do that.   if you have just one alembic_version table and multiple sub-projects, then you use multiple bases: https://alembic.sqlalchemy.org/en/latest/branches.html#working-with-multiple-bases


So Alembic has at least two built-in ways to address the general concept of what you're doing.   Otherwise it's not clear what you mean by "Store the submodule version_num somewhere", and if "op" is not imporatble that means you are likely doing some kind of deep patching / reorganzation so I don't have any answer for that short of supporting new API use cases.

**Comment by yoobles** [comment]
Essentially I have a plugin architecture where submodules can be added by end users and those submodules may create tables which also need migrations.

The main project has its `version_num` table but each submodule will need its own as well since they're not exactly based off of the main `version_num`.

I can't use multiple environments as the main project doesn't know the path of the submodule. Multiple bases seems closer but I'm unsure if it supports my use case.

Currently I am running migrations by creating my own `op` instance and passing it manually to the `upgrade` function and then saving the new head in a separate table.

**Comment by yoobles** [comment]
From some very light testing I do not think multiple bases works for my use case either. 

- I don't know the full submodule path ahead of time so I can't put the right value in `alembic.ini`. I only know the parent directory for all installed submodules. 
- It looks like the current version_num after upgrade becomes the version_num specified in one of the branches. This doesn't make sense for my project where the main project's version_num is the correct current for the whole project and the submodules should have a seperate version_num being tracked. 

Thus I think my usecase needs custom code so I'll keep using my weird solution. Thanks for responding and please point out if I'm misunderstanding anything!

**Comment by zzzeek** [comment]
yes, what you're describing is not Alembic's architecture so I can't offer much here than what the API currently has.
