### ISSUE TITLE
I seem to need to call engine.dispose

### ISSUE THREAD

**Issue by hartzell** [sqlalchemy/alembic#702]
**Describe the bug**

My automated test case is unable to drop the test database unless I arrange for `env.py` to call `engine.dispose` because something is holding an connection connection.  The test case in the example below.

See https://github.com/sqlalchemy/alembic/issues/25#issuecomment-635689158 for background.

**Expected behavior**

I expect to be able to close the database without needing to call engine.displose.

**To Reproduce**

I've assembled a test case in [this repository](https://github.com/hartzell/alembic-issue-25).

The README.md describes it in more detail, including how to reproduce the issue.

Here's a sample run:

```shellsession
$ make veryclean
rm -rf \
alembic/__pycache__ \
alembic/versions/__pycache__ \
tests/__pycache__
rm -rf deps
$ make setup
mkdir deps
poetry install
Creating virtualenv alembic-issue-25-XD3-Gl9B-py3.7 in deps/virtualenvs
Installing dependencies from lock file


Package operations: 18 installs, 0 updates, 0 removals

  - Installing zipp (3.1.0)
  - Installing importlib-metadata (1.6.0)
  - Installing markupsafe (1.1.1)
  - Installing pyparsing (2.4.7)
  - Installing six (1.15.0)
  - Installing attrs (19.3.0)
  - Installing mako (1.1.2)
  - Installing more-itertools (8.3.0)
  - Installing packaging (20.4)
  - Installing pluggy (0.13.1)
  - Installing py (1.8.1)
  - Installing python-dateutil (2.8.1)
  - Installing python-editor (1.0.4)
  - Installing sqlalchemy (1.3.17)
  - Installing wcwidth (0.1.9)
  - Installing alembic (1.4.2)
  - Installing psycopg2 (2.8.5)
  - Installing pytest (5.4.2)
$ poetry run make test
PGURI=postgresql://postgres:example@localhost/issue_25_$$ pytest -v -s tests/issue-25.py
=========================================== test session starts ===========================================
platform linux -- Python 3.7.6, pytest-5.4.2, py-1.8.1, pluggy-0.13.1 -- /local_scratch/george.hartzell/tmp/alembic-issue-25/deps/virtualenvs/alembic-issue-25-XD3-Gl9B-py3.7/bin/python
cachedir: .pytest_cache
rootdir: /local_scratch/george.hartzell/tmp/alembic-issue-25, inifile: setup.cfg
collected 1 item

tests/issue-25.py::test_success INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 98c5a08793e3, create work_queue tables
PASSEDINFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running downgrade 98c5a08793e3 -> , create work_queue tables

tests/issue-25.py::test_success ERROR

================================================= ERRORS ==================================================
____________________________________ ERROR at teardown of test_success ____________________________________
tests/issue-25.py:42: in manage_test_db
    cur.execute(f"drop database {db}")
E   psycopg2.errors.ObjectInUse: database "issue_25_25261" is being accessed by other users
E   DETAIL:  There are 2 other sessions using the database.
========================================= short test summary info =========================================
ERROR tests/issue-25.py::test_success - psycopg2.errors.ObjectInUse: database "issue_25_25261" is being ...
======================================= 1 passed, 1 error in 5.48s ========================================
make: *** [test] Error 1
$
```

**Versions.**
 - OS:  centos 7
 - Python: 3.7.6
 - Alembic: 1.4.2
 - SQLAlchemy: 1.3.17
 - Database: postgresql 11.2
 - DBAPI: ?

**Additional context**

**Have a nice day!**

You too!

**Comment by zzzeek** [comment]
OK I am really not a fan of running someone's entire application, however, the claim being made here is very unusual since I dont see anything wrong with the env.py, although I do see raw use of psycopg2 elsewhere which is likely where the problem is originating from.    I had to install "poetry", which I don't use, and I see you mentioning docker, note that my current machine is Fedora 31 so cannot run docker images, only podman.   I dont see how to configure a database URL correcltly, I tried to configure the one in the Makefile but that seems to be a raw PG URL.

so I am getting:

```
tests/issue-25.py::test_success ERROR

================================================================================ ERRORS ================================================================================
____________________________________________________________________ ERROR at setup of test_success ____________________________________________________________________
tests/issue-25.py:33: in manage_test_db
    conn = psycopg2.connect(uri_without_db(uri))
deps/virtualenvs/alembic-issue-25-Zf9-W2sU-py3.8/lib/python3.8/site-packages/psycopg2/__init__.py:127: in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
E   psycopg2.OperationalError: FATAL:  password authentication failed for user "postgres"
======================================================================= short test summary info ========================================================================
ERROR tests/issue-25.py::test_success - psycopg2.OperationalError: FATAL:  password authentication failed for user "postgres"
=========================================================================== 1 error in 0.27s ===========================================================================
make: *** [Makefile:8: test] Error 1

```

I would really appreciate if you could distill your issue into an Alembic-only one that isn't using raw psycopg2 connect as well as esoteric tools like Poetry and requiring docker containers and a full git clone.  The use of psycopg2 connect elsewhere is likely why you are having a problem.    Take a look at Postgresql pg_stat_activity when it hangs and that will show where it is hanging.

**Comment by zzzeek** [comment]
OK I've looked at waht you have here, and you are simply trying to run a full DROP DATABASE at the end.  so yes, that is a very unusual case and you need to call engine.dispose(), because there are database connections that still refer to this database.  This is not surprising, now that I see what you're doing, and IMO it's not a bug.    Alembic is meant to work on existing databases and then exit.  if you are running it in some kind of harness where A. you need to drop the DB (unusual!) and B. you are leaving the Alembic process running (more unusual!) then you need to dispose all connections, or use NullPool with the engine.

**Comment by hartzell** [comment]
Thank you for digging into it!

I didn't:

- Mean that you had to run the docker image to get postgresql, or use poetry, or ....  I just didn't understand enough about what was going on to figure out how to trim it down any further.
- Mean that you had to use poetry, but the pyproject.toml tells you exactly what I was using at the top level and the lock file contains excruciating detail about the entire graph, so it seemed to have potential usefulness.
- Make you run an entire app, but the test suite was what was failing and I didn't understand *etc...*.
- (*Definitely* didn't) mean to suggest that it was a bug, just that I was finding that I *did* need to call `dispose` and you were telling me in no uncertain terms that I didn't and I couldn't reconcile the two.

While it may seem like I dumped a thoughtless ball of mud into your lap, it *did* take me a good bit of work to tease the demo out of the thing that I'm building at work.

FWIW, the application that I'm building is a CLI that uses click and includes subcommands to run database migrations.  Rather than require people run alembic separately it wraps calls to `alembic.config.main`.  At some point it might be worth making it run the migrations automagically, but that requires gaining confidence in my migrations and our deployment strategy.

My test suite starts from scratch, creating a database (by opening a connection and running DDL commands; I suppose I could shell out to createdb/dropdb, but that's another dependency) and migrating it up to where it needs to be.  It uses the same routines to do that that the CLI uses (dogfooding 101).  So I'm not "keeping Alembic running", it's just the global state hanging around after `alembic.config.main()` has exited that's tripping me up.

Encouraged by your comment above I figured out how to hook up a NullPool and that also solves the problem.  It feels a bit neater too.

**Thank you again** for clearing up the mystery.

**Comment by zzzeek** [comment]
OK the thing about the "mcve" is that I usually cannot figure out why an error is occurring just by reading code, I have to run it and debug it myself.    so that's why we ask for these cases, most of the time I really have to run the code.

the confusion for me is when on the other issue you used the phrase "drop the database", for test suites I usually imagine that means dropping all the tables.    I'm not a big "DROP DATABASE" type so that did not occur to me.

I see what you're doing and it's totally fine.     I'm literally juggling 10-12 differnt issues / features at the same time each day so i dont always have a pinpoint accurate response for everything coming at me.  thanks for your patience.

**Comment by hartzell** [comment]
Thanks!  Appreciate the time you invest and the things you share!
