### ISSUE TITLE
MSSQL via ODBC has string type mismatch for sqlalchemy queries vs alembic table creation in Airflow

### ISSUE THREAD

**Issue by alexmc-ms** [sqlalchemy/alembic#739]
**Describe the bug**
If I go to the migrations in Airflow and type 'alembic upgrade head', alembic will create tables using VARCHAR.  However, sqlalchemy queries to those tables will show as NVARCHAR queries in MSSQL making them very inefficient.

**Expected behavior**
I don't expect there to be a type mismatch.  I expect alembic to use the same types when creating the tables as sqlalchemy will use to query the tables (preferably NVARCHAR for String types).

**To Reproduce**
Please try to provide a [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) example, with the migration script and/or the SQLAlchemy tables or models involved.
See also [Reporting Bugs](https://www.sqlalchemy.org/participate.html#bugs) on the website.

The alembic migrations for Airflow can be found here: https://github.com/apache/airflow/tree/master/airflow/migrations/versions.

1. Using airflow, type 'airflow initdb'.  This will call alembic and create the tables.
2. Using airflow, type 'airflow webserver'. Opening the web page should cause a query to Airflow since it will try to get the DAGs from the database.
3. Inspecting any sqlalchemy String column created by alembic, such as the dag_id column in the dag_run table will show the type as VARCHAR.
4. Inspecting any String queries from Airflow to the dag_run table will show the type used as NVARCHAR.

I created a simple app in order to create the tables outside of airflow (though airflow is still required since some of the versions import it).

```py
from sqlalchemy import create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker

engine = create_engine('mssql+pyodbc://<login>:<password>@<server>:1433/<databse>?driver=ODBC+Driver+17+for+SQL+Server')

Base = declarative_base()
```

**Error**

```
# Copy error here. Please include the full stack trace.
```

**Versions.**
 - OS: Linux Debian9 (custom kernel)
 - Python: 3.7.6
 - Alembic: 1.4.0
 - SQLAlchemy: 1.3.13
 - Database: Azure Sql Server database
 - DBAPI:

**Additional context**

**Have a nice day!**
Any help or insight on this is appreciated.  Thank you.

**Comment by CaselIT** [comment]
Hi, thanks for reporting this.

Some example code or specific link would have been appreciated.
If I understand it correctly the problem is that the migration generates the `VARCHAR` type for `String` columns, but for the same table the `String` columns are treated as `NVARCHAR` by sqlalchemy when running queries?

**Comment by zzzeek** [comment]
I think you are likely seeing the common pyodbc issue which is that because Python strings are Unicode,  pyodbc binds these to the driver as NVARCHAR.  Otherwise if you could share what you mean by "sqlalchemy queries to those tables will show as NVARCHAR queries in MSSQL" that would be helpful ; it is not typical that any datatype is shown in a SQL query unless CAST is being used which would be an explicit thing.

Assuming you are having the NVARCHAR binding issue and you'd prefer to use all NVARCHAR, the solution is simple which is to ensure you are creating tables with NVARCHAR, and not VARCHAR, which means you use the Unicode datatype and not String: https://docs.sqlalchemy.org/en/13/core/type_basics.html?highlight=unicode#sqlalchemy.types.Unicode

Hopefully this will resolve your issue.

**Comment by alexmc-ms** [comment]
Thank you zzzeek.  I was not aware that pyodbc is the one that is binding the strings as NVARCHAR.  This is very useful to know.

I am using Apache Airflow.  The database flow is Apache Airflow -> sqlalchemy -> pyodbc -> unixodbc -> Microsoft TDS. I wasn't sure at which layer this interpretation of String to NVARCHAR was happening.  I mistakenly assumed sqlalchemy was interpreting String differently than alembic and had hoped perhaps there was some way to get alembic to interpret it the same way.  I knew there was the option of using Unicode to force alembic to use NVARCHAR, but Apache Airflow produces all of the migrations already using String.  I will take this information back to the Apache Airflow community.

In the meantime, I have implemented your suggested solution for now which is to patch all of the Apache Airflow alembic migrations from String to Unicode on my system before creating the database tables.

Thank you.  I appreciate your quick response.

**Comment by alexmc-ms** [comment]
I realized after closing this, I have another question regarding this.

Why isn't alembic also using pyodbc when it calls MS SQL to create the tables given the sqlalchemy URL I gave it?

engine = create_engine('**mssql+pyodbc**://<login>:<password>@<server>:1433/<databse>?driver=ODBC+Driver+17+for+SQL+Server')

**Comment by zzzeek** [comment]
So there's a difference here between the SQL strings that are passed to the database driver, and the way in which the driver accommodates specific Python values.

A quick scan through https://www.python.org/dev/peps/pep-0249/ might make this clearer.

when alembic creates a table, it sends a srtring to the driver, such as:

```
cursor.execute("CREATE TABLE mytable (data VARCHAR(50))")
```

that name "VARCHAR" is there because you would have used the String datatype.   That logic has nothing to do with the driver.

Later, when you run a query on this table, SQLAlchemy sends a command like this to pyodbc:


```
cursor.execute("SELECT data FROM mytable WHERE data=%s", {"data", u"Some data"})
```

That is, at the "SQL String" level there's no mention of VARCHAR or NVARCHAR or anything like that.   We pass your Python data right through as a **parameter** to the database driver (pyodbc).   pyodbc then sees that ``u"some data"`` is a Python unicode object, which is the case for all strings in Python 3.   pyodbc, when it talks to your odbc driver, tells the odbc driver, "I have a parameter here named "data" and you should treat it as an NVARCHAR".  So that's what the driver does, which is very specific to how ODBC works, and then SQL Server has this very specific not-very-good behavior which is that it can't reconcile the NVARCHAR parameter against the VARCHAR index on the table, and that's how you get your problem.

**Comment by alexmc-ms** [comment]
I see.  That's a great explanation.  Thank you.
