### ISSUE TITLE
Rebase

### ISSUE THREAD

**Issue by ahonnecke** [sqlalchemy/alembic#744]
**Is your feature request related to a problem? Please describe.**
Not a problem as such, but a feature that would save me time.  I find myself manually recreating migrations to avoid a merge migration because it seems "cleaner" and more clear.  So this is based on my preference for a linear migration chain.

**Describe the solution you'd like**
I think that a command that would automatically "rebase" a merged, effectively performing a task that I do manually would be helpful.  The proposed command would take the form of:

`alembic rebase <revision or filename or file path>`

Running it would "move" that migration to the head of the revision stack, with the down revision of the newly "rebased" migration being the current head.  The way I effect this now is to copy the up and down methods of the migration I want to rebase, delete the file, make a new migration with the same name and then replace the up and down methods with the copy from earlier.

**Additional context**
I would be interested in contributing to effect this feature.

**Have a nice day!**

**Comment by CaselIT** [comment]
Hi @ahonnecke I've moved the issue in the alembic repository

**Comment by zzzeek** [comment]
if you can confirm the operation is like this:


Bdown -> B -> downB -> D

alembic rebase B

Bdown -> downB -> D -> B

1. for a given revision B, locate all migration files that contain B as their immediate "down" revision, call these downB

2. For revision B, retrieve its own "down" revision, call this Bdown

3. alter all files in downB so that their "down" revision refers to Bdown

4. locate the current head D

5. alter the SHA in B to be a new migration

6. alter B to refer to D as its parent

7. note that the operation includes the *deletion of a sha from the revision tree*

Confirm above?

Questions:

1. what is the interaction with the database?  it seems that if a database is at or ahead of the revision in question, the effect is catastrophic:

a. moving the revision upwards means it's a change the DB already has, will be applied a second time and break

b. we want to implement history version table in #309, we can't delete from this

The reason "merge" isn't a problem like this is that we don't actually reorder anything.

if we just make the change destructive and don't really worry about the state of the DB and assume the user knows what they're doing, OK.  there can be any number of DBs

**Comment by ahonnecke** [comment]
That's an excellent point, I had not thought about the ramifications of deleting a sha from the revision tree.  My use case is only safe for unreleased migrations.  Perhaps we could check on the migration head and refuse to rebase any migrations that have been applied?

**Comment by zzzeek** [comment]
we can do that but this is still not very industrial strength as the alembic environment is intended to be used on any number of production databases.   I think we'd just have to work out a workflow that makes it clear this is only for new migraitons coming into the migration stream and perhaps it should be a direct alternative/ option to merge() in the first place, why not?

**Comment by zzzeek** [comment]
like `alembic merge --rebase` and you just have to make sure things do what you expect.

**Comment by zzzeek** [comment]
we dont' have plans to implement this however if folks want to get involved we can get back into it.

**Comment by ChannyClaus** [comment]
hi - i'm interested in picking this up. the scope of what i'm hoping to add is maybe a bit more narrow and specific, though.

we have a repository containing alembic-based migrations with a fair amount of daily updates. naturally, whenever the main branch moves forward, existing open PRs have to rebase, which is somewhat difficult to automate (unless we rely on `alembic merge heads`. we try to avoid it in an attempt to maintain a linear history).

to be absolutely clear, the scenario described above looks something like this:
```
main branch: (revision None->a) -> (revision a->b) -> (revision b->c)
feature branch 1: (revision c->d1)
feature branch 2: (revision c->d2)
```
if feature branch 1 merges, the above becomes:
```
main branch: (revision None->a) -> (revision a->b) -> (revision b->c) -> (revision c->d1)
feature branch 2: (revision c->d2)
```
at which point the author of feature branch 2 would have to manually edit their revision to be (d1 -> d2).

it would be nice if we could have `alembic rebase d1 d2`, where it in-place edits the existing revision to point to `d1` as its parent (and errs if there are multiple heads). more specifically, `alembic rebase d1 d2` will take the above state to:

```
main branch: (revision None->a) -> (revision a->b) -> (revision b->c) -> (revision c->d1)
feature branch 2: (revision d1->d2)
```

**Comment by zzzeek** [comment]
my current issue is im trying to understand what my thinking was four years ago at https://github.com/sqlalchemy/alembic/issues/744#issuecomment-702338826 , where I started with a series of migrations that were already linear, and it then picks "B" all by itself out of the tree like that.   I vaguely recall I was thinking pretty deeply at that time but it's not clicking at the moment.

the concern is always baking in a feature that has some behavior that we find is wrong, then we have to revert it.  that happens when we fail to wrap our heads around the use case in a totally general way, thinking of every possible scenario.   

right now it looks like we are talking about something that reads the revision history from the filesystem and changes some hash down values.   but as mentioned above it also could render existing history tables as unworkable for a database that already moved forward.   the goal here is to prevent doing something that sends people back here complaining about it.

**Comment by ChannyClaus** [comment]
> my current issue is im trying to understand what my thinking was four years ago at [#744 (comment)](https://github.com/sqlalchemy/alembic/issues/744#issuecomment-702338826) , where I started with a series of migrations that were already linear, and it then picks "B" all by itself out of the tree like that. I vaguely recall I was thinking pretty deeply at that time but it's not clicking at the moment.
> 
> the concern is always baking in a feature that has some behavior that we find is wrong, then we have to revert it. that happens when we fail to wrap our heads around the use case in a totally general way, thinking of every possible scenario.
> 
> right now it looks like we are talking about something that reads the revision history from the filesystem and changes some hash down values. but as mentioned above it also could render existing history tables as unworkable for a database that already moved forward. the goal here is to prevent doing something that sends people back here complaining about it.

yeah, definitely understand wanting to be more cautious. the way i envision this new feature is somewhat similar to `git rebase` (both in terms of its functionality and culture around it); it is often confusing and dangerous to those who don't understand it fully, but for those who do, it is immensely useful.

if `alembic` as a project strongly prefers to not introduce features that could be a foot gun to the users, i think that's perfectly fair. i just felt the use case i described above is probably fairly common since most orgs (if not all) i've seen keep their migration history almost always completely linear.

**Comment by zzzeek** [comment]
this is literally just some use of the alembic API and then modifying some files (though the modification part might have to make some assumptions about the file syntax).  so it's fine to start with an external proof of concept and then propose it be added as a command, i dont think it would be a lot of code.

**Comment by ChannyClaus** [comment]
made a POC here https://github.com/ChannyClaus/alembic-rebase/tree/main

seems to work pretty nicely, although it feels a little hacky/clunky since it makes a lot of assumptions about the structure of the revision files, etc (which, i presume, isn't going to change often but still isn't quite "the right thing" to do).

**Comment by zzzeek** [comment]
OK I see this part

https://github.com/ChannyClaus/alembic-rebase/blob/67dc401cbe0cb4258ad04427b2852e31289ecd32/rebase.py#L18-L25

you can break that out and use [walk_revisions](https://alembic.sqlalchemy.org/en/latest/api/script.html#alembic.script.ScriptDirectory.walk_revisions) , read the source to `command.branches` to see how it works.   there should be no need to parse strings like that, that's really brittle

**Comment by zzzeek** [comment]
like I would not be using command.XYZ with a stdout buffer.   just read the source to each command and use `ScriptDirectory` APIs the way the commands do

**Comment by ChannyClaus** [comment]
i agree it's brittle and i replaced that part of the implementation using `ScriptDirectory` where appropriate. is there a way to do the down revision edit programmatically as well?

separate topic, but is there a reason why these `alembic.command` API just dumps to stdout by default (seems to me like it's equivalent to just shelling out `alembic <command>` + kind of defeats the purpose of having python API)?

**Comment by zzzeek** [comment]
shelling out is more involved than calling command.xyz() but I think there's a bit of a split between the commands that "do something" like upgrade/downgrade and the ones that give information like branches/heads etc.    those alembic.command functions are invoked directly from the command line script so they are oriented towards acting like unix commands
