### ISSUE TITLE
UUID primary key leads to delayed anonymous unique constraint

### ISSUE THREAD

**Issue by jblachly** [sqlalchemy/alembic#793]
**Describe the bug**

_Summary: When using UUID as primary key in SQL Alchemy, Alembic correctly detects this and generates a correct migration. However, the NEXT migration erroneously includes the creation of an anonymous uniqueness constraint on `id`._

When using UUID as a primary key in SQL Alchemy, Alembic correctly detects this and generates a migration:

```
import uuid

from sqlalchemy import Column, VARCHAR  # all caps is SQL standard/vendor-neutral
from sqlalchemy.dialects.postgresql import UUID

from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class Test(Base):
    __tablename__ = "test"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

    text = Column(VARCHAR(length=255), nullable=False)
```

Generating a revision (`alembic revision --autogenerate -m test1`) functions correctly:

```
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('text', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###
```

However, a subsequent revision generation (for example, even immediately with no further changes) always adds an anonymous unique constraint on the primary key:

```
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'test', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test', type_='unique')
    # ### end Alembic commands ###
```

The first migration correctly creates the `(tablename)_pkey` uniqueness constraint, at least on Postgresql, whether or not I specify `unique=True` in the SQLAlchemy definition:

        id = Column(UUID(as_uuid=True), primary_key=True, unique=True, default=uuid.uuid4)

which, when specified, causes Alembic to emit an extra line: 

    sa.UniqueConstraint('id')

which does not affect the actual database in any way (at least for my database and driver) since the `(tablename)_pkey` uniquness constraint would have been created anyway.

Interestingly, when when using an integer primary key this behavior does not occur.

**Expected behavior**
I expect alembic to detect a primary key uniqueness constraint; it does detect this for integer primary keys, but not UUID.

I do not expect a spurious / duplicate unique constraint to be generated on a subsequent migration.

**To Reproduce**
Reproducible example included above.

**Error**

n/a (although of course if you d'nt notice the anonymous constraint, you cannot downgrade without error unless you manually insert the tablename_pkey uniqueness constraint name into the downgrade block)

**Versions.**
 - OS: 
 - Python: 3.7.6
 - Alembic: 1.5.3
 - SQLAlchemy: 1.3.23
 - Database: Postgresql 10
 - DBAPI: psycopg2

**Have a nice day!**

You too :)

**Comment by zzzeek** [comment]
hey there -

no unique constraint is reproduced here and I'm not aware of any reason that such a constraint would be detected, rev one looks like:

```
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "test",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("text", sa.VARCHAR(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###

```

rev two:

```
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

```

false positive issues are usually because something is being reflected or not reflected on the database side that does not match the model, typically indexes and unique constraints, but the model given doesn't have any unique constraints in the Python side.  you can confirm this by printing them out:


```python
>>> import uuid
>>> from sqlalchemy import Column, VARCHAR  # all caps is SQL standard/vendor-neutral
>>> from sqlalchemy.dialects.postgresql import UUID
>>> from sqlalchemy.ext.declarative import declarative_base
>>> Base = declarative_base()
>>> class Test(Base):
...     __tablename__ = "test"
...     id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
...     text = Column(VARCHAR(length=255), nullable=False)
... 
>>> Test.__table__.constraints
{PrimaryKeyConstraint(Column('id', UUID(as_uuid=True), table=<test>, primary_key=True, nullable=False, default=ColumnDefault(<function uuid4 at 0x7f46d162c9d0>)))}

```

Above there's just the PrimaryKeyConstraint which does not imply any UniqueConstraint.  The model as given will not have any unique constraints in it, and there's no logic in the PostgrreSQL impl that would add such a constraint.

so....you want to check that your model doesn't have anything else going on, like event hooks or extensions that might be interacting, or anything in your env.py, etc.

**Comment by jblachly** [comment]
Pretty bone-stock installation in relatively new project dir. I'll try to create a reproducible repository. Thank you.

**Comment by jblachly** [comment]
https://github.com/jblachly/alembic_test

Only changes to alembic.ini and env.py include database connection string and an update to `sys.path`.

The second revision yields:
```
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.ddl.postgresql] Detected sequence named 'testint_id_seq' as owned by integer column 'testint(id)', assuming SERIAL and omitting
INFO  [alembic.autogenerate.compare] Detected added unique constraint 'None' on '['id']'
INFO  [alembic.autogenerate.compare] Detected added unique constraint 'None' on '['id']'
  Generating /private/tmp/alembic_test/alembic/versions/06cfaa72376a_.py ...  done
``` 

I did make two mistakes for which I apologize:

1. I was mistaken stating that adding `unique=True` has no effect. In further testing, the bug (i.e., delayed unique constraint addition) is _only_ triggered when passing `unique=True` to the PK column. Not sure what happened during my initial reporting.
2. The bug additionally manifests even on integer PK columns -- when adding `unique=True`

**Comment by zzzeek** [comment]
hey there -

so the "bug" is in some combination of PostgreSQL itself and/or your program.     

Firstly, the [unique=True](https://docs.sqlalchemy.org/en/13/core/metadata.html?highlight=column%20unique#sqlalchemy.schema.Column.params.unique) flag is intended to add a UNIQUE constraint to the table, and here we see it is working correctly.   There is no reason I'm aware of that one would want to do this for a column that is already the single member of the PRIMARY KEY, as the PRIMARY KEY constraint already enforces uniqueness.    So to fix the "bug", you would remove this flag from your column.   

Secondly,  PostgreSQL does not apply simple UNIQUE constraints that are added to a primary key column, they are silently ignored (see below), whether or not they are given a name.   So your initial UNIQUE constraint is correctly passed to the database schema by Alembic, is ignored by PostgreSQL, and then when Alembic autogenerates again, the constraint continues to be "missing".

So whether or not point 1 or 2 is the "bug", Alembic and SQLAlchemy are just in the middle here, your instruction to create a separate UNIQUE constraint is ignored.


UNIQUE constraints are ignored; create these three tables.  Table t1 and t3 contain UNIQUE constraints that mirrors the primary key; t1's is unnamed as in the example here, t3's is named.  Table t2 has a UNIQUE constraint on a non-primary key column:

```sql
psql (12.4)
Type "help" for help.

test=> CREATE TABLE t1 (
test(> id UUID NOT NULL, 
test(> text VARCHAR(255) NOT NULL, 
test(> PRIMARY KEY (id), 
test(> UNIQUE (id)
test(> );
CREATE TABLE
test=> 
test=> CREATE TABLE t2 (
test(> id UUID NOT NULL, 
test(>     some_other_id UUID,
test(> text VARCHAR(255) NOT NULL, 
test(> PRIMARY KEY (id), 
test(> UNIQUE (some_other_id)
test(> );
CREATE TABLE
test=> 
test=> 
test=> CREATE TABLE t3 (
test(> id UUID NOT NULL, 
test(> text VARCHAR(255) NOT NULL, 
test(> PRIMARY KEY (id), 
test(> CONSTRAINT my_unique_constraint UNIQUE (id)
test(> );
CREATE TABLE

```

then, here's an approximation of the SQL query SQLAlchemy uses to see the unique constraints.  Only t2 returns a constraint; t1 and t3 do not:

```sql

test=>  SELECT
test->       tab.relname, 
test->         cons.conname as name,
test->         cons.conkey as key,
test->         a.attnum as col_num,
test->         a.attname as col_name
test->     FROM
test->         pg_catalog.pg_constraint cons
test->         join pg_attribute a
test->             on cons.conrelid = a.attrelid AND
test->             a.attnum = ANY(cons.conkey)
test->         join (
test(>             SELECT c.oid, c.relname
test(>             FROM pg_catalog.pg_class c
test(>             LEFT JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
test(>             WHERE (pg_catalog.pg_table_is_visible(c.oid))
test(>             AND c.relname IN('t1', 't2') AND c.relkind in
test(>             ('r', 'v', 'm', 'f', 'p')            
test(>         ) AS tab ON tab.oid=cons.conrelid
test->     WHERE cons.contype = 'u'
test-> ;
 relname |         name         | key | col_num |   col_name    
---------+----------------------+-----+---------+---------------
 t2      | t2_some_other_id_key | {2} |       2 | some_other_id
(1 row)

```

Alembic/ SQLAlchemy's only other options would be to 1. raise an error if unique=True is present, which I think is not appropriate because if your PK were composite, or the constraint had other options on it, or if the unqiue constraint were added as an explicit UniqueConstraint, or if this were a different database etc., it *may* be appropriate, i think it's best that it emits the DDL requested   and 2. Alembic would be able to guess that a unique of this nature is ignored by PostgreSQL in any case, which is mostly the same set of complexities as number 1, and I think it's best both tools simply do what they're told.

**Comment by jblachly** [comment]
@zzzeek I see the dilemma. It's a shame that including this flag, while redundant but not strictly wrong (my interpretation), is not idempotent. I'll take the easy way out and simply remove the parameter as you suggest.

Thanks for your help and very detailed explanation; feel free to close unless you are still contemplating a way to resolve the inconsistency.

**Comment by zzzeek** [comment]
the ultimate solution which might happen someday is we dont use the database for autogenerate e.g. #117
