### ISSUE TITLE
UnboundLocalError while command.init / alembic init

### ISSUE THREAD

**Issue by flapili** [sqlalchemy/alembic#808]
**Describe the bug**

`UnboundLocalError: local variable 'config_file' referenced before assignment` is raised when there is no alembic.ini.mako file in the template when we do a `command.init(...)`

**To Reproduce**

```py
command.init(config=alembic_cfg, directory="foo", template="default", package=True)
```
where templates/default/alembic.ini.mako doesn't exists

**Error**

```
Traceback (most recent call last):
  File ".\modularapi\cli.py", line 33, in <module>
    r = command.init(config=alembic_cfg, directory="foo", template="default", package=True)
  File "C:\Users\DEVEAUX\AppData\Local\Programs\Python\Python38\lib\site-packages\alembic\command.py", line 95, in init
    "settings in %r before proceeding." % config_file
UnboundLocalError: local variable 'config_file' referenced before assignment```



With your permission can I propose a PR if it's not a wont-fix ?
**Have a nice day!**

**Comment by zzzeek** [comment]
hi -

I don't understand the issue.   Alembic templates require the .mako file to be present.   I can't reproduce any problem otherwise:

```
from alembic.config import Config
from alembic import command
alembic_cfg = Config("./alembic.ini")
command.init(alembic_cfg, directory="bar", template="generic", package=True)

```

it seems like you want Alembic to do something that it's not designed to do, and we don't have development resources to pursue radical new directions for how Alembic works,  so you would need to provide a more comprehensive architecture for what you want to do.   Let's keep the discussion at #807 if that's OK, thanks.
