### ISSUE TITLE
Addition of a string Enum member is half of the times not detected and when detected the migration script does not work

### ISSUE THREAD

**Issue by dactrungnguyen** [sqlalchemy/alembic#826]
**Describe the bug**
Autogenerate detects addition of a string Enum member if and only if it is longer than current members

**Expected behavior**
Addition of a string Enum member is detected what ever the length of the new member, and the autogenerated script works.

**To Reproduce**
Column:
```py
state = Column(Enum(enums.RunState, native_enum=False), nullable=False, default=enums.RunState.PENDING)
```
Previous Enum:
```py
class RunState(str, Enum):
    PENDING = 'PENDING'
    RUNNING = 'RUNNING'
    DONE = 'DONE'
    FAILED = 'FAILED'
```
Bugs: 
* If I add to the Enum `POUF = 'POUF'`, Alembic does NOT detect the change, if I add `POUFPOUFPOUF = 'POUFPOUFPOUF'` instead, Alembic does.
* In the latter case where change is detected, generated migration script does not work : Alembic considers existing type to be VARCHAR(7) without constraint :
```py
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('runs', 'state',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('PENDING', 'RUNNING', 'DONE', 'FAILED', 'POUFPOUF', name='runstate', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###
```
This script, when invoked with `alembic upgrade head`, does not work.
That should be VARCHAR(7) with constraint, i.e. a non-native Enum:
```py
def upgrade():
    # manually modified
    op.alter_column('runs', 'state',
               existing_type=sa.Enum('PENDING', 'RUNNING', 'DONE', 'FAILED', name='runstate', native_enum=False),
               type_=sa.Enum('PENDING', 'RUNNING', 'DONE', 'FAILED', 'POUFPOUF', name='runstate', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###
```
This script worked.

**Versions.**
 - OS: Xubuntu 20.04
 - Python: 3.7.5
 - Alembic: 1.5.8
 - SQLAlchemy: 1.3.16
 - Database: Postgresql
 - DBAPI: psycopg2

**Additional context**

**Have a nice day!**

**Comment by zzzeek** [comment]
hey there -

this would be #363, part of the entire range of ENUM issues, none of which are automated right now, as for all three kinds (PG native, MySQL native, non-native), there are difficult and awkward problems involved (and all different).    The "create_constraint" feature of Enum has been defaulted to False in SQLAlchemy 1.4 due to the problems it creates in this area.   I'm kind of surprised the column length part of it seems to be working though.      you would need to edit your migration files manually for now.

we continue to be open to motivated contributors who would want to problem solve in the area of enumerated types.
