### ISSUE TITLE
_ProxyTransaction.__exit__ fails after call to _ProxyTransaction.rollback

### ISSUE THREAD

**Issue by estandiaa-marain** [sqlalchemy/alembic#829]
**Describe the bug**
We are using this approach (suggested in [this Stack Overflow answer](https://stackoverflow.com/a/59704406/15269094)) to do a dry-run for the alembic upgrade
```python
with connectable.connect() as connection:
    context.configure(
        connection=connection, target_metadata=target_metadata
    )
    with context.begin_transaction() as transaction:
        context.run_migrations()
        if 'dry-run' in context.get_x_argument():
            print('Dry-run succeeded; now rolling back transaction...')
            transaction.rollback()
```
This used to work fine for our PostgreSQL database until recently.

**Expected behavior**
The DB upgrade is rolled back.

**To Reproduce**
See the code above. The key line is the call to `transaction.rollback()`. If this line is called when the `transaction` context manager is active, then an error is thrown when the `__exit__` method is called.

**Error**

```
File "<python_path>/lib/python3.7/site-packages/alembic/runtime/migration.py", line 44, in __exit__
    self._proxied_transaction.__exit__(type_, value, traceback)
AttributeError: 'NoneType' object has no attribute '__exit__'
```

The problem seems to be that `_ProxyTransaction.rollback` sets `self.migration_context._transaction = None` which then throws an error when `_ProxyTransaction.__exit__` runs `self._proxied_transaction.__exit__(type_, value, traceback)`

**Versions.**
 - OS: Ubuntu 20.04.2 LTS 
 - Python: 3.7.7
 - Alembic: 1.5.8
 - SQLAlchemy: 1.3.23
 - Database: PostgreSQL 13.2
 - DBAPI: I am not sure what this is

**Additional comments**
This is my first issue in this repo. Please let me know if I missed anything or if you need any additional information. I am happy to provide more details.

Thank you in advance.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Ensure proxy transaction still present on exit before closing** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/2756

**Comment by zzzeek** [comment]
thanks for reporting.     This won't be released until 1.6.0 for which I have another large change to merge still, so for now I would advise either staying on 1.4.x or you might try a temporary workaround like:

```
    with context.begin_transaction() as transaction:
        context.run_migrations()
        transaction._proxy_transaction.rollback()
```

**Comment by estandiaa-marain** [comment]
Thanks for the quick response. The workaround that works great!

**Comment by jiyolla** [comment]
> you need to be on a backend that uses transactional DDL or otherwise set the transactional_ddl flag to True, this confused me as well just now. i've updated the SO answer as well as the above description. code looks like:
> 
> ```python
> with connectable.connect() as connection:
>     context.configure(
>         connection=connection, target_metadata=target_metadata,
>         transactional_ddl=True
>     )
>     with context.begin_transaction() as transaction:
>         context.run_migrations()
>         if 'dry-run' in context.get_x_argument():
>             print('Dry-run succeeded; now rolling back transaction...')
>             transaction.rollback()
> ```

Sry for the late reply.

That worked! Thank you very much.
Glad to know that you are the author of the SO answer.
It's that SO post lead me here.

**Comment by jiyolla** [comment]
Since you are also the maintainer of the alembic,
may I ask when is it supposed to do such 'dry run'?

I initially searched for 'dry run', because I wasn't sure that the handwritten part of migration scripts will work as expected and I do not want to the untested code to possibly damage my database.

But it seems that if anything goes wrong the rollback procedure is automatically started.
Is this true?
If it's true, then when should I use the dry-run?
Maybe when the migration is not 'illegal'(so no error raised and thus no rollback) but not as 'intended'?
Then possibly one will run some extra code(like printing some sample rows, or metadatas) before rollback to make sure the migration worked as intended?
But that would mean quite frequent modification of 'env.py', if the double-checking process is not general enough and rather as per migration.

**Comment by zzzeek** [comment]
you perhaps could use "dry run" to test your migration as you are adding new things to it.   usually this would be in an environment where "downgrades" aren't being implemented for whatever reason.   the rationale given in the stackoverflow answer is when running a migration against a production database that otherwise succeeded in development scenarios.  id strongly recommend having an accurate staging copy of the production environment instead of that, but every situation is different.

**Comment by jiyolla** [comment]
> you perhaps could use "dry run" to test your migration as you are adding new things to it. usually this would be in an environment where "downgrades" aren't being implemented for whatever reason. the rationale given in the stackoverflow answer is when running a migration against a production database that otherwise succeeded in development scenarios. id strongly recommend having an accurate staging copy of the production environment instead of that, but every situation is different.

Thanks for the quick reply.
I should have read the question description in SO more carefully.
