### ISSUE TITLE
Add --exit-zero argument

### ISSUE THREAD

**Issue by PerchunPak** [sqlalchemy/alembic#999]
**Describe the use case**

I want use, alembic auto-generate in my `Makefile`, but if there are no new changes - alembic exit with non-zero code.

**Databases / Backends / Drivers targeted**

The best, will be to add this argument for all possible commands, not only `alembic revision`.

**Example Use**

```sh-session
$ alembic revision --autogenerate --exit-zero
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
ERROR [alembic.util.messaging] Target database is not up to date.
  FAILED: Target database is not up to date.
$ echo $?
0
```

**Comment by PerchunPak** [comment]
Fixed by:
```
alembic revision --autogenerate || true
```
But argument also will be nice.

**Comment by zzzeek** [comment]
hi there -

your paragraph and your example show two different things:

1. a non-zero code if autogenerate runs, but there were no model changes detected (why would that be an error?)
2. a non-zero code if autogenerate runs, but cannot run because the target database is up to date.  this should already be returning a non-zero error code as this raises CommandError, which is caught by the util.err() routine which calls sys.exit(-1)
3. "will be to add this argument for all possible commands, " unclear what this would mean.  Alembic should be returning non-zero error code for all error conditions.   The initial request seems to be that "autogenerate found no new changes" should be an error condition, which it's not so I would not favor implementing this.

**Comment by PerchunPak** [comment]
I saw this option in [flake8](https://flake8.pycqa.org/en/latest/user/options.html#cmdoption-flake8-exit-zero), which force flake8 to use the exit status code 0 even if there are errors. This is what I mean.

**Comment by zzzeek** [comment]
oh, you want autogenerate's -1 code to be squashed.    then you use the `|| true` bash technique.  There's no need for that to be an option in the tool itself, it's much clearer to use the idiomatic pattern.   I have no idea why flake8 has such an option, it's redundant.

**Comment by zzzeek** [comment]
the author of flake8 [regrets](https://twitter.com/codewithanthony/status/1500838724401344516) adding this option.  so please use `|| true`, thanks!
